br/urls.py
#!/usr/bin/env python
# vim: ai ts=4 sts=4 et sw=4
from django.conf.urls import url
from django.http import HttpResponseRedirect

from br import views
from br.api.views import dashboard as api_dashboard
from unicefng.backend import HttpBackendView

urlpatterns = [
    url(r'^incoming/', HttpBackendView.as_view(backend_name='polling')),
    url(r'^api/v1/?$', api_dashboard, name='api_dashboard'),
    url(r'^help/?$', views.FAQView.as_view(), name='help'),
    url(r'^projections/?$', views.ProjectionDashboardView.as_view(), name='projection'),
    url(r'^reports/?$', views.ReportListView.as_view(), name='reports_list'),
    url(r'^report/(?P<pk>\d+)/?$', views.ReportEditView.as_view(),
        name='report_edit'),
    url(r'^report/(?P<pk>\d+)/delete$', views.ReportDeleteView.as_view(),
        name='report_delete'),
    url(r'^reports/delete/?$', views.br_report_delete, name=u'rep_delete'),
    url(r'^map/?$', views.map_dashboard, name='map_dashboard'),

    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^(?P<year>\d+)/?$', views.dashboard, name='dashboard_with_year'),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/?$', views.dashboard,
        name='dashboard_with_year_and_month'),
    url(r'^(?P<state>[a-z\-]+)/?$', views.dashboard,
        name='dashboard_with_state'),
    url(r'^(?P<state>[a-z\-]+)/(?P<year>\d+)/?$', views.dashboard,
        name='dashboard_with_state_and_year'),
    url(r'^(?P<state>[a-z\-]+)/(?P<year>\d+)/(?P<month>\d+)/?$', views.dashboard,
        name='dashboard_with_state_year_and_month'),
]

locations/urls.py
#!/usr/bin/env python
# vim: ai ts=4 sts=4 et sw=4
from django.conf.urls import url
from locations import views

urlpatterns = [
    url(r'^center/new/?$', views.CenterCreationView.as_view(), name='center_add'),
    url(r'^centers/?$', views.CenterListView.as_view(), name='center_list'),
    url(r'^non-reporting-centers/?$', views.NonReportingCentresView.as_view(), name='non_reporting_center_list'),
    url(r'^center/(?P<pk>\d+)/?$', views.CenterUpdateView.as_view(), name='center_edit'),
]

unicefng/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from unicefng.backend import HttpBackendView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # RapidSMS core URLs
    # url(r'^accounts/', include('rapidsms.urls.login_logout')),
    # RapidSMS contrib app URLs
    url(r'^httptester/', include('rapidsms.contrib.httptester.urls')),
    url(r'^messagelog/', include('rapidsms.contrib.messagelog.urls')),
    url(r'^messaging/', include('rapidsms.contrib.messaging.urls')),
    url(r'^registration/', include('rapidsms.contrib.registration.urls')),

    # Third party URLs
    url(r'^selectable/', include('selectable.urls')),
    url(r'^br/', include('br.urls', namespace=u'br')),
    url(r'^dr/', include('dr.urls', namespace=u'dr')),
    url(r'^locations/', include('locations.urls', namespace=u'locations')),
    url(r'^api/v2/', include('vitalregpro.urls', namespace=u'apiv2')),
    url(r'^api/', include('api.urls', namespace=u'api')),
    url(r'^mnchw/', include('campaigns.urls', namespace=u'mnchw')),
    url(r'incoming/', HttpBackendView.as_view(backend_name='polling')),
    url(r'^messages/', include('messagebox.urls', namespace='messaging')),
    url(r'^reporters/', include('reporters.urls', namespace=u'reporters')),
    url(r'^users/', include('profiles.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# authentication urls
urlpatterns += [
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'backend/login.html'}, name="user-login"),
    url(r'^accounts/logout/$', auth_views.logout_then_login, name="user-logout")
]

locations/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4
import networkx as nx
from django.conf import settings
from django.core.cache import cache, caches, InvalidCacheBackendError
from django.db import connection, models
from mptt.models import MPTTModel, TreeForeignKey

from common.constants import DATA_SOURCES, DATA_SOURCE_INTERNAL


class Search(models.Lookup):
    lookup_name = 'search'

    def as_mysql(self, compiler, connection):
        lhs, lhs_params = self.process_lhs(compiler, connection)
        rhs, rhs_params = self.process_rhs(compiler, connection)
        params = lhs_params + rhs_params

        return 'MATCH (%s) AGAINST (%s)' % (lhs, rhs), params


models.CharField.register_lookup(Search)
models.TextField.register_lookup(Search)


class LocationType(models.Model):
    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Type"

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.__unicode__()


class Location(MPTTModel):
    """A Location is technically a geopgraphical point (lat+long), but is often
       used to represent a large area such as a city or state. It is recursive
       via the _parent_ field, which can be used to create a hierachy (Country
       -> State -> County -> City) in combination with the _type_ field."""

    type = models.ForeignKey(LocationType, related_name="locations", blank=True, null=True)
    name = models.CharField(max_length=100, help_text="Name of location", db_index=True)
    code = models.CharField(max_length=30, unique=True)
    population = models.PositiveIntegerField(default=0, null=False, blank=False)

    parent = TreeForeignKey("Location", related_name="children", null=True, blank=True,
        help_text="The parent of this Location. Although it is not enforced, it" +\
                  "is expected that the parent will be of a different LocationType")

    latitude = models.DecimalField(max_digits=8, decimal_places=6, blank=True, null=True, help_text="The physical latitude of this location")
    longitude = models.DecimalField(max_digits=8, decimal_places=6, blank=True, null=True, help_text="The physical longitude of this location")

    lft = models.PositiveIntegerField(blank=True, default=0, db_index=True)
    rgt = models.PositiveIntegerField(blank=True, default=0, db_index=True)
    tree_id = models.PositiveIntegerField(blank=True, default=0, db_index=True)
    level = models.PositiveIntegerField(blank=True, default=0, db_index=True)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    source = models.CharField(
        max_length=32, choices=DATA_SOURCES, default=DATA_SOURCE_INTERNAL)
    vrp_id = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        if hasattr(self, 'type') and self.type:
            return "%s %s" % (self.name, self.type.name)
        else:
            return self.name

    def __str__(self):
        return self.__unicode__()

    class Meta:
        ordering = ['name']

    class MPTTMeta:
        left_attr = 'lft'
        right_attr = 'rgt'
        tree_id_attr = 'tree_id'
        level_attr = 'level'
        order_insertion_by = ['code']

    # TODO: how can we port the Location.contacts and Location.one_contact
    #       methods, now that the locations app has been split from reporters?
    #       even if they can import one another, they can't know if they're
    #       both running at parse time, and can't monkey-patch later.
    def one_contact(self, role, display=False):
        return ""

    @classmethod
    def get_by_code(cls, code):
        try:
            return cls.objects.get(code=code)
        except cls.DoesNotExist:
            return None

    @classmethod
    def _get_locations_graph(cls, reverse=False):
        if reverse:
            if not hasattr(cls, '_reversed_locations_graph'):
                cls._reversed_locations_graph = get_locations_graph(reverse)
            return cls._reversed_locations_graph
        else:
            if not hasattr(cls, '_locations_graph'):
                cls._locations_graph = get_locations_graph()
            return cls._locations_graph

    @classmethod
    def _subnodes(cls, node, type):
        graph = cls._get_locations_graph()
        descendant_ids = nx.topological_sort(graph, graph.subgraph(nx.dfs_tree(graph, node['id']).nodes()).nodes())

        if type:
            return (graph.node[i] for i in descendant_ids if graph.node[i]['type'] == type)
        else:
            return (graph.node[i] for i in descendant_ids)

    def contacts(self, role=None):
        return Location.objects.get(pk=2)

    def ancestors(self, include_self=False):
        """Returns all of the parent locations of this location,
           optionally including itself in the output. This is
           very inefficient, so consider caching the output.

           This is currently used as a convenience method as recent
           versions of django-mptt handle this adequately."""

        return self.get_ancestors(include_self=include_self)

    def descendants(self, include_self=False):
        """Returns all of the locations which are descended from this location,
           optionally including itself in the output. This is very inefficient
           (it recurses once for EACH), so consider caching the output.

           New improvements, please see doc for ancestors method."""

        return self.get_descendants(include_self=include_self)

    @property
    def node(self):
        graph = self._get_locations_graph()
        return graph.node[self.pk]

    def nx_descendants(self, include_self=False):
        graph = self._get_locations_graph()
        descendant_ids = nx.topological_sort(graph, graph.subgraph(nx.dfs_tree(graph, self.id).nodes()).nodes())
        if include_self:
            return [graph.node[id] for id in descendant_ids]
        else:
            return [graph.node[id] for id in descendant_ids if id != self.id]

    def nx_ancestors(self, include_self=False):
        reversed_graph = self._get_locations_graph(reverse=True)
        ancestor_ids = nx.topological_sort(reversed_graph, reversed_graph.subgraph(nx.dfs_tree(reversed_graph, self.id).nodes()).nodes())
        if include_self:
            return [reversed_graph.node[id] for id in ancestor_ids]
        else:
            return [reversed_graph.node[id] for id in ancestor_ids if id != self.id]

    def nx_children(self):
        reversed_graph = self._get_locations_graph()
        children_ids = reversed_graph.successors(self.id)
        return [reversed_graph.node[id] for id in children_ids]

    def _get_annual_population_estimate(self, year):
        result = None

        if self.type.name not in ('Country', 'State', 'LGA'):
            return result

        try:
            result = self.census_results.filter(location=self, year__lte=year).latest('year')
        except Exception:
            return result
        diff = year - result.year
        projection = result.population * ((1 + (result.growth_rate / 100.0)) ** diff)

        return int(round(projection))

    def center_count(self):
        return self.get_descendants(include_self=True).filter(type__name='RC').count()

    def get_annual_population_growth_estimate(self, year):
        # previous_projection = self._get_annual_population_estimate(year - 1)
        # current_projection = self._get_annual_population_estimate(year)

        # return int(round(current_projection - previous_projection))

        return self._get_annual_population_estimate(year)

    def get_monthly_population_growth_estimate(self, year):
        # previous_projection = self._get_annual_population_estimate(year - 1)
        # current_projection = self._get_annual_population_estimate(year)

        # return int(round((current_projection - previous_projection) / 12.0))

        return int(round(self._get_annual_population_estimate(year) / 12.0))

    def get_stock(self):
        from supply.models import Stock
        try:
            stock = Stock.objects.get(location=self)
        except Stock.DoesNotExist:
            stock = None

        return stock
    
    def latest_birth_report_time(self):
        if self.type.name != 'RC':
            return None
        
        try:
            report = self.birthregistration_records.latest('time')

            return report.time
        except Exception:
            return None


def get_locations_graph(reverse=False):
    try:
        app_cache = caches['graphs']
    except InvalidCacheBackendError:
        app_cache = cache

    graph = app_cache.get('reversed_locations_graph') if reverse else app_cache.get('locations_graph')
    if not graph:
        if reverse:
            graph = generate_locations_graph().reverse()
            app_cache.set('reversed_locations_graph', graph, settings.LOCATIONS_GRAPH_MAXAGE)
        else:
            graph = generate_locations_graph()
            app_cache.set('locations_graph', graph, settings.LOCATIONS_GRAPH_MAXAGE)
    return graph


def generate_locations_graph():
    location_qs = Location.objects.order_by('level', 'name').values(
        'pk', 'name', 'parent__pk', 'type__name', 'active')
    graph = nx.DiGraph()

    for loc_info in location_qs.filter(parent__pk=None):
        graph.add_node(
            loc_info['pk'],
            name=loc_info['name'],
            id=loc_info['pk'],
            type=loc_info['type__name'],
            active=loc_info['active'])

    for loc_info in location_qs.exclude(parent__pk=None):
        graph.add_node(
            loc_info['pk'],
            name=loc_info['name'],
            id=loc_info['pk'],
            type=loc_info['type__name'],
            active=loc_info['active'])

locations/forms.py
import calendar

from django import forms

from br.utils import get_report_year_range
from locations.models import Location


def generate_edit_form(location, data=None):
    state_choices = Location.objects.filter(type__name='State').values_list(
        'id', 'name')

    def clean_location_field(form, field_name, location_type):
        loc_id = form.cleaned_data[field_name]
        try:
            Location.objects.get(pk=loc_id, type__name=location_type)
        except Location.DoesNotExist:
            raise forms.ValidationError('Invalid {}'.format(location_type))

        return loc_id

    class CenterEditForm(forms.Form):
        id = forms.IntegerField(widget=forms.HiddenInput())
        name = forms.CharField(max_length=100)
        code = forms.CharField(max_length=100)
        state = forms.ChoiceField(choices=state_choices)
        lga = forms.IntegerField(widget=forms.HiddenInput())
        active = forms.BooleanField(required=False)

        def clean_lga(self):
            return clean_location_field(self, 'lga', 'LGA')

        def clean(self):
            cleaned_data = super(CenterEditForm, self).clean()
            code = cleaned_data.get('code')
            location = None
            try:
                location = Location.objects.get(code=code)
            except Location.DoesNotExist:
                pass

            if location and (location.pk != cleaned_data.get('id')):
                self._errors['code'] = self.error_class(
                    'Code already in use for an existing location')
                del cleaned_data['code']

            return cleaned_data

    if data is None:
        ancestors = location.get_ancestors()
        data = {
            'id': location.pk,
            'name': location.name,
            'code': location.code,
            'state': ancestors.get(type__name='State').pk,
            'lga': ancestors.get(type__name='LGA').pk,
            'active': location.active
        }

    return CenterEditForm(data)


class CenterGroupCreationForm(forms.Form):
    center_data = forms.CharField(widget=forms.HiddenInput())


class CenterCreationForm(forms.Form):
    name = forms.CharField()
    lga = forms.ModelChoiceField(queryset=Location.objects.filter(
        type__name=u'LGA'))


def _get_year_choices():
    choices = [('', '----- Select year -----')]
    year_range = get_report_year_range()
    choices.extend([(yr, yr) for yr in range(year_range[0], year_range[1] + 1)])
    return choices


def _get_month_choices():
    choices = [('', '----- Select month -----')]
    choices.extend([(i, calendar.month_abbr[i]) for i in range(1, 13)])
    return choices


class NonReportingCentresFilterForm(forms.Form):
    location = forms.ModelChoiceField(queryset=Location.objects.filter(type__name__in=['State', 'LGA']), required=False)
    year = forms.ChoiceField(choices=_get_year_choices, required=False)
    month = forms.ChoiceField(choices=_get_month_choices, required=False)

locations/templates/locations/center_create_get.html
{% extends "br/base.html" %}
{% load bootstrap3 location_tags %}
{% load pipeline staticfiles %}
{% block stylesheets %}
{% stylesheet 'centers' %}
{% endblock %}
{% block title %}{{ page_title }}{% endblock %}
{% block content %}
<div class="container">
	<div class="row filter">
	</div>
	<div class="row">
		<div class="col-md-12" id="grid"></div>
	</div>
	<div class="row">
		<form method="POST">
			<div class="col-md-12">
				{% csrf_token %}
				{{ group_form }}
				<p>&nbsp;</p>
			</div>
			<div class="col-md-12">
				<button id="post_location_data" type="button" class="btn btn-primary">Save</button>
				<p id="locations" data-locations="{{ location_data }}">&nbsp;</p>
			</div>
		</form>
	</div>
</div>
{% endblock %}
{% block scripts %}
{% javascript 'centers' %}
<script>
	var container = document.getElementById('grid');
	var location_data = JSON.parse(document.getElementById('locations').dataset.locations);
	var states = [];
	for (var prop in location_data)
		if (location_data.hasOwnProperty(prop))
			states.push(prop);

	function onChange(changes, source) {
		if (!changes)
			return;

		var instance = this;
		changes.forEach(function(change) {
			var row = change[0];
			var col = change[1];
			var newValue = change[3];
			var cellProperties, options;

			if (col == 'state') {
				cellProperties = instance.getCellMeta(row, 1);
				setDropdownSource.call(instance, row, newValue);
				instance.render();
			}
		});
	}

	function setDropdownSource (row, value) {
		var instance = this;
		var options = location_data[value];
		var cellProperties = instance.getCellMeta(row, 1);
		cellProperties.source = options;
	}

	var handsOnTable = new Handsontable(container, {
		data: [],
		dataSchema: {state: null, lga: null, name: null, code: null},
		startRows: 10,
		startCols: 4,
		colHeaders: ['State', 'LGA', 'Name', 'Code'],
		columns: [
			{data: 'state', type: 'dropdown', source: states},
			{data: 'lga', type: 'dropdown'},
			{data: 'name'},
			{data: 'code'}
		],
		minSpareRows: 1,
		stretchH: 'all',
		afterChange: onChange
	});

	function onSubmit () {
		var form = this.form;
		var center_data = handsOnTable.getData().slice(0, -1);  // remove extra empty row
		form.elements['center_data'].value = JSON.stringify(center_data);
		form.submit();
	}

	var submitBtn = document.getElementById('post_location_data');
	submitBtn.onclick = onSubmit;
</script>
{% endblock %}

locations/templates/locations/center_create_post.html
{% extends "br/base.html" %}
{% load bootstrap3 location_tags %}
{% load pipeline staticfiles %}
{% block stylesheets %}
{% stylesheet 'centers' %}
{% endblock %}
{% block title %}{{ page_title }}{% endblock %}
{% block content %}
<div class="container">
	<div class="row filter">
		<div class="col-md-12">
			<table class="table table-striped table-bordered">
				<caption>Results</caption>
				<thead>
					<tr>
						<th>State</th>
						<th>LGA</th>
						<th>Name</th>
						<th>Code</th>
						<th>Message</th>
					</tr>
				</thead>
				<tbody>
				{% if creation_log %}
				{% for log in creation_log %}
				<tr class="{% if log.success %}success{% else %}danger{% endif %}">
					
					<td>{{ log.state|default_if_none:'N/A' }}</td>
					<td>{{ log.lga|default_if_none:'N/A' }}</td>
					<td>{{ log.name|default_if_none:'N/A' }}</td>
					<td>{{ log.code|default_if_none:'N/A' }}</td>
					<td>{{ log.message }}</td>
				</tr>
				{% endfor %}
				{% else %}
				<tr class="warning">
					<td colspan="5">No centers created</td>
				</tr>
				{% endif %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}
{% block scripts %}
{% javascript 'centers' %}
{% endblock %}

locations/templates/locations/center_edit.html
{% extends 'base/layout.html' %}
{% load pipeline staticfiles widget_tweaks %}
{% block stylesheets %}
{% stylesheet 'centers' %}
{% endblock %}
{% block title %}{{ page_title }}{% endblock %}
{% block content %}
<div class="container">
    <div class="row filter">
        <div class="col-md-12">
            <form class="form-horizontal" method="POST">
                {% csrf_token %}
                {{ form.id }}
                <div class="form-group">
                    <label for="{{ form.name.name }}">{{ form.name.label }}</label>
                    {% render_field form.name class='form-control' %}
                </div>
                <div class="form-group">
                    <label for="{{ form.code.name }}">{{ form.code.label }}</label>
                    {% render_field form.code class='form-control' %}
                </div>
                <div class="form-group">
                    <label for="{{ form.state.name }}">{{ form.state.label }}</label>
                    {% render_field form.state class='form-control' %}
                </div>
                <div class="form-group">
                    <label for="{{ form.lga.id_for_label }}">{{ form.lga.label|upper }}</label>
                    <select name="{{ form.lga.name }}" id="{{ form.lga.id_for_label }}">
                        <option selected="true" value="{{ location.parent.pk }}">{{ location.parent.name }}</option>
                    </select>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            {{ form.active }} {{ form.active.label }}
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-default" href="{% url 'locations:center_list' %}">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
{{ block.super }}
{% javascript 'centers' %}
<script type="text/javascript">
$(document).ready(function() {
    var endpoint = "{% url 'api:location_list_typed' %}?type=lga&parent={{ location.parent.parent.pk }}";
    $('#id_state').select2({
        width: 'resolve'
    });
    $('#id_lga').select2({
      ajax: {
        data: function(params) {
          return {q: params.term};
        },
        dataType: 'json',
        delay: 250,
        processResults: function(data, params) {
          return {results: data.results};
        },
        url: endpoint
      },
      allowClear: true,
      minimumInputLength: 2,
      width: '150px',
      placeholder: 'Location',
      templateResult: function(item) {
        return item.name;
      },
      templateSelection: function(item) {
        if (item.text)
          return item.text;
        else
          return item.name;
      }
    });
});
</script>
{% endblock %}

locations/templates/locations/center_list.html
{% extends 'base/layout.html' %}{% load bootstrap_pagination location_tags static %}
{% block title %}Birth Registration Statistics &middot; {{ page_title }}{% endblock %}
{% block usermenu %}
{% include 'common/usermenu.html' %}
{% endblock %}
{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'css/select2/select2.min.css' %}">
<style type="text/css">
    .select2-container.form-control {
        display: inline-block;
    }
</style>
{% endblock %}
{% block masthead %}
<div class="row">
    <div class="col-lg-12 title">
        <ol class="breadcrumb">
            <li><a href="{% url "br:dashboard" %}">Birth Registration</a></li>
            <li class="active">Birth Registration Centers</li>
        </ol>
        <h1 class="page-title">Birth Registration Centers</h1>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        {% if messages %}
        <section class="widget">
        <div class="widget-body">
        {% for message in messages %}
        <p class="alert {{ message.extra_tags }}">{{ message }}</p>
        {% endfor %}
        </div>
        </section>
        {% endif %}
        <section class="widget">
            <form class="form-horizontal form-inline" role="form" id="filter_form">
                <fieldset>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <select class="select2 form-control" id="{{ filter_form.lga.id_for_label }}" name="{{ filter_form.lga.name }}" data-placeholder="LGA">
                                {% if filter_form.cleaned_data.lga %}<option value="{{ filter_form.cleaned_data.lga.pk }}">{{ filter_form.cleaned_data.lga.name }}</option>{% endif %}
                            </select>
                            <button type="submit" class="btn btn-primary" id="filter_button">Filter</button>
                            <a class="btn btn-inverse" href="{% url 'locations:center_list' %}">Clear</a>
                            
                        </div>
                    </div>
                </fieldset>
            </form>
        </section>
        {% if perms.locations.add_location %}<section class="widget"><a href="{% url 'locations:center_add' %}" class="btn btn-success">Add new</a></section>{% endif %}
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <section class="widget">
            <div class="widget-table">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>State</th>
                            <th>LGA</th>
                            <th>Name</th>
                            <th>Code</th>
                            <th>Active</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for center in centers %}
                        {% with ancestors=center.get_ancestors %}
                        <tr>
                            <td>{{ ancestors|extract_ancestor_name:'State' }}</td>
                            <td>{{ ancestors|extract_ancestor_name:'LGA' }}</td>
                            <td>{{ center.name }}</td>
                            <td>{{ center.code }}</td>
                            {% if center.active %}
                            <td class="success"><i class="glyphicon glyphicon-ok"></i></td>
                            {% else %}
                            <td class="danger"><i class="glyphicon glyphicon-remove"></i></td>
                            {% endif %}
                        </tr>
                        {% endwith %}
                        {% empty %}
                        <tr>
                            <td class="table-warning text-xs-center" colspan="5">No centers found</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="text-xs-center">
            {% bootstrap_paginate page_obj range=10 show_first_last="true" %}
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
{{ block.super }}
<script src="{% static "js/select2/select2.min.js" %}"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    var endpoint = '{% url "api:location_list_typed" %}?type=lga';
    $('#{{ filter_form.lga.id_for_label }}').select2({
        ajax: {
            url: endpoint,
            data: function(params) {
              return {q: params.term};
            },
            dataType: 'json',
            quietMillis: 250,
            processResults: function(data, params) {
              return {results: data.results};
            }
        },
        width: '30em',
        allowClear: true,
        minimumInputLength: 2,
        cache: true,
        templateResult: function(item) {
            return item.name + ' (' + item.type + ')';
        },
        templateSelection: function(item) {
            if (item.text)
                return item.text;
            else
                return item.name + ' (' + item.type + ')';
        }
    });
});
</script>
{% endblock %}