br/urls.py
#!/usr/bin/env python
# vim: ai ts=4 sts=4 et sw=4
from django.conf.urls import url
from django.http import HttpResponseRedirect

from br import views
from br.api.views import dashboard as api_dashboard
from unicefng.backend import HttpBackendView

urlpatterns = [
    url(r'^incoming/', HttpBackendView.as_view(backend_name='polling')),
    url(r'^api/v1/?$', api_dashboard, name='api_dashboard'),
    url(r'^help/?$', views.FAQView.as_view(), name='help'),
    url(r'^projections/?$', views.ProjectionDashboardView.as_view(), name='projection'),
    url(r'^reports/?$', views.ReportListView.as_view(), name='reports_list'),
    url(r'^report/(?P<pk>\d+)/?$', views.ReportEditView.as_view(),
        name='report_edit'),
    url(r'^report/(?P<pk>\d+)/delete$', views.ReportDeleteView.as_view(),
        name='report_delete'),
    url(r'^reports/delete/?$', views.br_report_delete, name=u'rep_delete'),
    url(r'^map/?$', views.map_dashboard, name='map_dashboard'),

    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^(?P<year>\d+)/?$', views.dashboard, name='dashboard_with_year'),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/?$', views.dashboard,
        name='dashboard_with_year_and_month'),
    url(r'^(?P<state>[a-z\-]+)/?$', views.dashboard,
        name='dashboard_with_state'),
    url(r'^(?P<state>[a-z\-]+)/(?P<year>\d+)/?$', views.dashboard,
        name='dashboard_with_state_and_year'),
    url(r'^(?P<state>[a-z\-]+)/(?P<year>\d+)/(?P<month>\d+)/?$', views.dashboard,
        name='dashboard_with_state_year_and_month'),
]

campaigns/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from campaigns import views
from ipd import views as ipd_views

urlpatterns = [
	url(r'^$', ipd_views.dashboard, name=u'dashboard'),
	url(r'^(?P<campaign_id>\d+)/(?P<location_id>\d+)/?$', ipd_views.dashboard,
		name=u'dashboard_detail'),
	url(r'^campaigns/?$', views.CampaignListView.as_view(), name=u'campaign_list'),
	url(r'^campaigns/new/?$', views.CampaignCreateView.as_view(), name=u'campaign_new'),
	url(r'^campaigns/(?P<campaign_id>\d+)/(?P<location_id>\d+)/reports/?$',
		ipd_views.ReportListView.as_view(), name=u'report_list'),
	url(r'^campaigns/(?P<pk>\d+)/?$',
		views.CampaignUpdateView.as_view(), name=u'campaign_update'),
	url(r'^reports/(?P<pk>\d+)/?$', ipd_views.ReportUpdateView.as_view(),
		name=u'report_update'),
]

unicefng/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from unicefng.backend import HttpBackendView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # RapidSMS core URLs
    # url(r'^accounts/', include('rapidsms.urls.login_logout')),
    # RapidSMS contrib app URLs
    url(r'^httptester/', include('rapidsms.contrib.httptester.urls')),
    url(r'^messagelog/', include('rapidsms.contrib.messagelog.urls')),
    url(r'^messaging/', include('rapidsms.contrib.messaging.urls')),
    url(r'^registration/', include('rapidsms.contrib.registration.urls')),

    # Third party URLs
    url(r'^selectable/', include('selectable.urls')),
    url(r'^br/', include('br.urls', namespace=u'br')),
    url(r'^dr/', include('dr.urls', namespace=u'dr')),
    url(r'^locations/', include('locations.urls', namespace=u'locations')),
    url(r'^api/v2/', include('vitalregpro.urls', namespace=u'apiv2')),
    url(r'^api/', include('api.urls', namespace=u'api')),
    url(r'^mnchw/', include('campaigns.urls', namespace=u'mnchw')),
    url(r'incoming/', HttpBackendView.as_view(backend_name='polling')),
    url(r'^messages/', include('messagebox.urls', namespace='messaging')),
    url(r'^reporters/', include('reporters.urls', namespace=u'reporters')),
    url(r'^users/', include('profiles.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# authentication urls
urlpatterns += [
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'backend/login.html'}, name="user-login"),
    url(r'^accounts/logout/$', auth_views.logout_then_login, name="user-logout")
]

base/models.py
from django.db import models

# Create your models here.

campaigns/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.timezone import now

from common.constants import DATA_SOURCES
from locations.models import Location


class Application(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Campaign(models.Model):
    PROGRAM_TYPES = {
        '1': 'May/June',
        '2': 'Nov/Dec',
    }

    name = models.CharField(max_length=255)
    locations = models.ManyToManyField(Location, limit_choices_to={
        u'type__name__in': [u'State', u'LGA']})
    start_date = models.DateField()
    end_date = models.DateField()
    apps = models.ManyToManyField(Application)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    source = models.CharField(
        choices=DATA_SOURCES, default=DATA_SOURCES[1][0], max_length=32)

    def __str__(self):
        return self.name

    def campaign_states(self):
        return self.locations.filter(type__name=u'State')

    def campaign_lgas(self, location):
        try:
            if self.locations.get(pk=location.pk) and location.type.name == u'State':
                return self.locations.filter(parent=location,
                    type__name=u'LGA') or location.children.all()
        except Location.DoesNotExist:
            pass

        return Location.objects.none()

    def get_related_objects(self, model_class, state, locations=None):
        try:
            if not locations:
                lgas = self.campaign_lgas(state)
                if lgas.count() == Location.objects.filter(parent=state).count():
                    return model_class.objects.filter(
                        location__code__startswith=state.code,
                        time__range=(self.start_date, self.end_date))
                else:
                    locations = state.get_descendants(include_self=True)

            return model_class.objects.filter(location__in=locations,
                time__range=(self.start_date, self.end_date))
        except Exception:
            pass

        return model_class.objects.none()

    @classmethod
    def active_campaigns(cls, location=None):
        date = now().date()
        qs = cls.objects.filter(start_date__lte=date, end_date__gte=date)

        if location is not None and isinstance(location, Location):
            return qs.filter(locations__lft__lte=location.lft,
                locations__rght__gte=location.rght)

        return qs

ipd/models.py
# -*- coding: utf-8 -*-
from django.db import models

from common.constants import DATA_SOURCES
from locations.models import Location
from reporters.models import PersistantConnection, Reporter


class Report(models.Model):
    IM_COMMODITIES = (
        ('opv', 'Oral Polio Vaccine'),
        ('vita', 'Vitamin A'),
        ('tt', 'Tetanus Toxoid'),
        ('mv', 'Measles Vaccine'),
        ('bcg', 'Bacille Calmette-Guerin Vaccine'),
        ('yf', 'Yellow Fever'),
        ('hepb', 'Hepatitis B'),
        ('fe', 'Iron Folate'),
        ('dpt', 'Diphtheria'),
        ('deworm', 'Deworming'),
        ('sp', 'Sulphadoxie Pyrimethanol for IPT'),
        ('plus', 'Plus'),
        ('hp', 'Health Promotion'),
        ('fp', 'Family Planning'),
        ('llin', 'Long Lasting Insecticide Nets'),
        ('muac', 'Measurement of Upper Arm Circumference'),
        ('penta', 'Pentavalent Vaccine'),
    )

    reporter = models.ForeignKey(Reporter, blank=True, null=True)
    connection = models.ForeignKey(PersistantConnection, blank=True, null=True)
    location = models.ForeignKey(Location)
    time = models.DateTimeField(db_index=True)
    immunized = models.PositiveIntegerField(blank=True, null=True,
        help_text=u'Total persons immunized')
    commodity = models.CharField(choices=IM_COMMODITIES, max_length=10,
        blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    source = models.CharField(
        choices=DATA_SOURCES, default=DATA_SOURCES[1][0], max_length=32)

    class Meta:
        permissions = (
            (u'can_view', u'Can view'),
        )

    def __str__(self):
        return u'{} ({}) => {}, {}'.format(self.location, self.reporter,
            self.commodity, self.immunized)


class NonCompliance(models.Model):
    NC_REASONS = (
        ('1', 'OPV Safety'),
        ('2', 'Child Sick'),
        ('3', 'Religious Belief'),
        ('4', 'No Felt Need'),
        ('5', 'Political Differences'),
        ('6', 'No Care Giver Consent'),
        ('7', 'Unhappy With Immunization Personnel'),
        ('8', 'Too Many Rounds'),
        ('9', 'Reason Not Given'),
    )

    reporter = models.ForeignKey(Reporter, blank=True, null=True)
    connection = models.ForeignKey(PersistantConnection, blank=True, null=True)
    location = models.ForeignKey(Location)
    time = models.DateTimeField(db_index=True)
    reason = models.CharField(choices=NC_REASONS, max_length=1, blank=True,
        null=True, help_text=u'The stated reason for non-compliance')
    cases = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    source = models.CharField(
        choices=DATA_SOURCES, default=DATA_SOURCES[1][0], max_length=32)


class Shortage(models.Model):
    SHORTAGE_COMMODITIES = (
        ('opv', 'OPV'),
        ('vita', 'Vitamin A'),
        ('tt', 'Tetanus Toxoid'),
        ('mv', 'Measles Vaccine'),
        ('yf', 'Yellow Fever'),
        ('hepb', 'Hepatitis B'),
        ('folate', 'Ferrous Folate'),
        ('dpt', 'Diphtheria'),
        ('deworm', 'Deworming'),
        ('sp', 'Sulphadoxie Pyrimethanol for IPT'),
        ('plus', 'Plus'),
    )

    reporter = models.ForeignKey(Reporter, null=True, blank=True)
    connection = models.ForeignKey(PersistantConnection, null=True, blank=True)
    location = models.ForeignKey(Location)
    time = models.DateTimeField(db_index=True)
    commodity = models.CharField(blank=True, null=True, max_length=10,
        choices=SHORTAGE_COMMODITIES,
        help_text=u'The commodity being reported as having a shortage')
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    source = models.CharField(
        choices=DATA_SOURCES, default=DATA_SOURCES[1][0], max_length=32)

    def __str__(self):
        return u'{} ({}) => {}'.format(self.reporter, self.location,
            self.commodity)

campaigns/forms.py
# -*- coding: utf-8 -*-
from django import forms

from campaigns.models import Campaign
from locations.models import Location


class CampaignCreateForm(forms.ModelForm):
    program = forms.ChoiceField(
        choices=Campaign.PROGRAM_TYPES.items(),
        widget=forms.widgets.RadioSelect)
    locations = forms.ModelMultipleChoiceField(
        queryset=Location.objects.filter(type__name__in=[u'LGA', u'State']),
        widget=forms.CheckboxSelectMultiple())
    start_date = forms.DateField(input_formats=['%d/%m/%Y'])
    end_date = forms.DateField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Campaign
        fields = (u'locations', u'start_date', u'end_date')


class CampaignUpdateForm(forms.ModelForm):
    start_date = forms.DateField(input_formats=['%d/%m/%Y'])
    end_date = forms.DateField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Campaign
        fields = (u'locations', u'start_date', u'end_date')

campaigns/views.py
# -*- coding: utf-8 -*-
from braces.views import LoginRequiredMixin, PermissionRequiredMixin
from django.core.urlresolvers import reverse
from django.db.models import F
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, ListView, UpdateView

from django.conf import settings

from campaigns.filters import CampaignFilterSet
from campaigns.forms import CampaignCreateForm, CampaignUpdateForm
from campaigns.models import Campaign, Location

PROTECTED_VIEW_PERMISSION = u'ipd.change_report'


class BaseCampaignViewMixin(LoginRequiredMixin, PermissionRequiredMixin):
    permission_required = PROTECTED_VIEW_PERMISSION

    def get_context_data(self, **kwargs):
        context = super(BaseCampaignViewMixin, self).get_context_data(**kwargs)

        context[u'page_title'] = self.page_title

        return context


class CampaignCreateView(BaseCampaignViewMixin, CreateView):
    form_class = CampaignCreateForm
    page_title = u'Create new campaign'
    template_name = u'campaigns/campaign_new.html'

    def form_valid(self, form):
        name = '{program} {year}'.format(
            program=Campaign.PROGRAM_TYPES.get(
                form.cleaned_data['program']),
            year=form.cleaned_data['start_date'].year)

        campaign = form.save(commit=False)
        campaign.name = name
        campaign.save()
        form.save_m2m()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse(u'mnchw:campaign_list')


class CampaignListView(BaseCampaignViewMixin, ListView):
    model = Campaign
    ordering = (u'-end_date',)
    page_title = u'Campaigns'
    paginate_by = settings.PAGE_SIZE
    template_name = u'campaigns/campaign_list.html'
    filter_class = CampaignFilterSet

    def get_context_data(self, **kwargs):
        context = super(CampaignListView, self).get_context_data(**kwargs)
        context[u'filter_form'] = self.filter.form

        return context

    def get_queryset(self):
        queryset = super(CampaignListView, self).get_queryset()

        self.filter = self.filter_class(self.request.GET, queryset=queryset)

        queryset = self.filter.qs.prefetch_related(u'locations').annotate(
            loc_pk=F(u'locations__pk'), loc_name=F(u'locations__name'),
            loc_type=F(u'locations__type__name')).values(u'pk', u'loc_pk',
            u'name', u'start_date', u'end_date', u'loc_name', u'loc_type')

        return queryset


class CampaignUpdateView(BaseCampaignViewMixin, UpdateView):
    form_class = CampaignUpdateForm
    model = Campaign
    page_title = u'Edit campaign'
    template_name = u'campaigns/campaign_update.html'

    def get_context_data(self, **kwargs):
        context = super(CampaignUpdateView, self).get_context_data(**kwargs)

        location_pks = context['form']['locations'].value()
        selected_locs = Location.objects.filter(pk__in=location_pks)

        context['selected_locations'] = selected_locs

        return context

    def get_success_url(self):
        return reverse(u'mnchw:campaign_list')

campaigns/templates/campaigns/base.html
{% extends 'common/base.html' %}
{% load bootstrap_pagination static %}
{% block stylesheets %}
{% endblock %}
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

campaigns/templates/campaigns/campaign_list.html
{% extends 'base/layout.html' %}{% load bootstrap_pagination static %}
{% block title %}MNCHW Statistics · Campaign List{% endblock %}
{% block usermenu %}
{% include 'common/usermenu.html' %}
{% endblock %}
{% block stylesheets %}
{{ block.super }}
<style type="text/css">
    .select2-container.form-control {
        display: inline-block;
    }
</style>
{% endblock %}
{% block masthead %}
<div class="row">
    <div class="col-lg-12 title">
        <ol class="breadcrumb">
            <li><a href="{% url "mnchw:dashboard" %}">MNCHW</a></li>
            <li class="active">MNCHW Campaigns</li>
        </ol>
        <h1 class="page-title">MNCHW Campaigns</h1>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <section class="widget">
            <form class="form-horizontal form-inline" role="form" id="filter_form">
                <fieldset>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <input type="hidden" id="{{ filter_form.location.id_for_label }}" name="{{ filter_form.location.name }}" data-placeholder="Location" class="select2 form-control" tabindex="-1">
                            <input id="{{ filter_form.start_date.id_for_label }}" type="text" placeholder="Start Date" name="{{ filter_form.start_date.name }}" class="form-control datepicker" value="{{ filter_form.start_date.value }}" />
                            <input id="{{ filter_form.end_date.id_for_label }}" type="text" placeholder="End Date" name="{{ filter_form.end_date.name }}" class="form-control datepicker" value="{{ filter_form.end_date.value }}" />
                            <button type="submit" class="btn btn-primary" id="filter_button">Filter</button>
                            <a class="btn btn-inverse" href="{% url 'mnchw:campaign_list' %}">Clear</a>
                        </div>
                    </div>
                </fieldset>
            </form>
        </section>
        {% if perms.campaigns.add_campaign %}<section class="widget"><a href="{% url 'mnchw:campaign_new' %}" class="btn btn-success">Add new</a></section>{% endif %}
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <section class="widget">
            <div class="widget-table">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Location</th>
                            <th></th>
                            {% if perms.campaigns.add_campaign %}<th></th>{% endif %}
                        </tr>
                    </thead>
                    <tbody>{% for campaign in object_list %}
                        <tr>
                            <td>{{ campaign.name }}</td>
                            <td>{{ campaign.start_date|date:'SHORT_DATE_FORMAT' }}</td>
                            <td>{{ campaign.end_date|date:'SHORT_DATE_FORMAT' }}</td>
                            <td>{{ campaign.loc_name }} ({{ campaign.loc_type }})</td>
                            <td><a href="{% url 'mnchw:report_list' campaign_id=campaign.pk location_id=campaign.loc_pk %}">View reports</a></td>
                            {% if perms.campaigns.add_campaign %}<td><a href="{% url 'mnchw:campaign_update' pk=campaign.pk %}">Edit</a></td>{% endif %}
                        </tr>{% empty %}
                        <tr>
                            <td class="table-warning text-xs-center" colspan="5">No campaigns found</td>
                        </tr>{% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="text-xs-center">
            {% bootstrap_paginate page_obj range=10 show_first_last="true" %}
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
{{ block.super }}
<script src="{% static "base/vendor/underscore/underscore-min.js" %}"></script>
<script src="{% static "base/vendor/select2/select2.min.js" %}"></script>
<script src="{% static "base/vendor/moment/min/moment.min.js" %}"></script>
<script src="{% static "base/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js" %}"></script>
<script type="text/javascript">
    $(function () {
        $('.datepicker').datetimepicker({
            format: 'MM/DD/YYYY'
        });
        var endpoint = '{% url "api:location_list_typed" %}?type=state,lga';
        $('#{{ filter_form.location.id_for_label }}').select2({
            ajax: {
                url: endpoint,
                data: function(term, page) {
                  return {q: term};
                },
                dataType: 'json',
                quietMillis: 250,
                results: function(data, page) {
                  return {results: data.results};
                }
            },
            width: '30em',
            // allowClear: true,
            minimumInputLength: 2,
            cache: true,
            formatResult: function(item) {
                return item.name + ' (' + item.type + ')';
            },
            formatSelection: function(item) {
                if (item.text)
                    return item.text;
                else
                    return item.name + ' (' + item.type + ')';
            }
        });
    });
</script>
{% endblock %}

campaigns/templates/campaigns/campaign_new.html
{% extends 'base/layout.html' %}{% load static %}
{% block title %}MNCHW · Create campaign{% endblock %}
{% block usermenu %}
{% include 'common/usermenu.html' %}
{% endblock %}
{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'css/select2/select2.min.css' %}">
<style type="text/css">
    .select2-container.form-control {
        display: inline-block;
    }
</style>
{% endblock %}
{% block masthead %}
<div class="row">
    <div class="col-lg-12 title">
        <ol class="breadcrumb">
            <li><a href="{% url "mnchw:dashboard" %}">MNCHW Dashboard</a></li>
            <li class="active">Create campaign</li>
        </ol>
        <h1 class="page-title">Create campaign</h1>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <section class="widget">
            <div class="widget-body">
                <form class="form-horizontal" role="form" method="post">{% csrf_token %}
                    <fieldset>
                        <legend><strong>Create campaign</strong></legend>
                        {% if form.errors %}
                        <div class="alert alert-danger">
                          <ul>
                            {% for err_field, field_errors in form.errors.iteritems %}
                            {% for err_msg in field_errors %}
                            <li>{{ err_field }}: {{ err_msg }}</li>
                            {% endfor %}
                            {% endfor %}
                          </ul>
                        </div>
                        {% endif %}
                        <div class="form-group row">
                          <label for="{{ form.program.id_for_label }}" class="col-md-3 form-control-label text-md-right">Program</label>
                          <div class="col-md-4">
                            {% for choice in form.program %}
                            <div class="radio">{{ choice }}</div>
                            {% endfor %}
                          </div>
                        </div>
                        <div class="form-group row">
                            <label for="locations" class="col-md-3 form-control-label text-md-right">Locations</label>
                            <div class="col-md-4">
                              <select class="select2 form-control" id="locations" name="{{ form.locations.name }}" data-placeholder="Locations">
                            </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="{{ form.start_date.id_for_label }}" class="col-md-3 form-control-label text-md-right">Start date</label>
                            <div class="col-md-4">
                              <input class="form-control datepicker" type="text" name="{{ form.start_date.name }}" id="{{ form.start_date.id_for_label }}" placeholder="Start date">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="{{ form.end_date.id_for_label }}" class="col-md-3 form-control-label text-md-right">End date</label>
                            <div class="col-md-4">
                              <input class="form-control datepicker" type="text" name="{{ form.end_date.name }}" id="{{ form.end_date.id_for_label }}" placeholder="End date">
                            </div>
                        </div>
                    </fieldset>
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-7">
                                <button type="submit" class="btn btn-primary form-control-lg">Save Changes</button>
                                <a href="javascript:history.go(-1);" class="btn btn-inverse form-control-lg">Cancel</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </section>
    </div>
</div>
{% endblock content %}
{% block scripts %}
{{ block.super }}
<script src="{% static "base/vendor/underscore/underscore-min.js" %}"></script>
<script src="{% static "base/vendor/moment/min/moment.min.js" %}"></script>
<script src="{% static "base/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js" %}"></script>
<script src="{% static "js/select2/select2.min.js" %}"></script>
<script type="text/javascript">
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    var endpoint = '{% url "api:location_list_typed" %}?type=state,lga';

    $('.datepicker').datetimepicker({
      format: 'DD/MM/YYYY'
    });

    $('#locations').select2({
      ajax: {
          url: endpoint,
          data: function(params) {
            return {q: params.term};
          },
          dataType: 'json',
          quietMillis: 250,
          processResults: function(data, params) {
            return {results: data.results};
          }
      },
      width: '100%',
      minimumInputLength: 2,
      multiple: true,
      placeholder: 'Locations',
      templateResult: function(item) {
        return item.name + ' (' + item.type + ')';
      },
      templateSelection: function(item) {
        if (item.text)
          return item.text;
        else
          return item.name + ' (' + item.type + ')';
      }
    });
  });
})();
</script>
{% endblock scripts %}

campaigns/templates/campaigns/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'mnchw:campaign_list' %}">MNCHWs</a>
</nav>