br/api/urls.py
# -*- coding: utf-8 -*-

br/urls.py
#!/usr/bin/env python
# vim: ai ts=4 sts=4 et sw=4
from django.conf.urls import url
from django.http import HttpResponseRedirect

from br import views
from br.api.views import dashboard as api_dashboard
from unicefng.backend import HttpBackendView

urlpatterns = [
    url(r'^incoming/', HttpBackendView.as_view(backend_name='polling')),
    url(r'^api/v1/?$', api_dashboard, name='api_dashboard'),
    url(r'^help/?$', views.FAQView.as_view(), name='help'),
    url(r'^projections/?$', views.ProjectionDashboardView.as_view(), name='projection'),
    url(r'^reports/?$', views.ReportListView.as_view(), name='reports_list'),
    url(r'^report/(?P<pk>\d+)/?$', views.ReportEditView.as_view(),
        name='report_edit'),
    url(r'^report/(?P<pk>\d+)/delete$', views.ReportDeleteView.as_view(),
        name='report_delete'),
    url(r'^reports/delete/?$', views.br_report_delete, name=u'rep_delete'),
    url(r'^map/?$', views.map_dashboard, name='map_dashboard'),

    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^(?P<year>\d+)/?$', views.dashboard, name='dashboard_with_year'),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/?$', views.dashboard,
        name='dashboard_with_year_and_month'),
    url(r'^(?P<state>[a-z\-]+)/?$', views.dashboard,
        name='dashboard_with_state'),
    url(r'^(?P<state>[a-z\-]+)/(?P<year>\d+)/?$', views.dashboard,
        name='dashboard_with_state_and_year'),
    url(r'^(?P<state>[a-z\-]+)/(?P<year>\d+)/(?P<month>\d+)/?$', views.dashboard,
        name='dashboard_with_state_year_and_month'),
]

messagebox/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import MessageListView

urlpatterns = [
    url(r'^$', MessageListView.as_view(), name='message_list'),
]

profiles/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from profiles.views import (
    UserCreateView, UserListView, UserUpdateView, user_delete)

urlpatterns = [
    url(r'^$', UserListView.as_view(), name='users_list'),
    url(r'^new/?$', UserCreateView.as_view(), name='user_create'),
    url(r'^delete/?$', user_delete, name='user_delete'),
    url(r'^(?P<pk>\d+)/?$', UserUpdateView.as_view(), name='user_edit'),
]

unicefng/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from unicefng.backend import HttpBackendView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # RapidSMS core URLs
    # url(r'^accounts/', include('rapidsms.urls.login_logout')),
    # RapidSMS contrib app URLs
    url(r'^httptester/', include('rapidsms.contrib.httptester.urls')),
    url(r'^messagelog/', include('rapidsms.contrib.messagelog.urls')),
    url(r'^messaging/', include('rapidsms.contrib.messaging.urls')),
    url(r'^registration/', include('rapidsms.contrib.registration.urls')),

    # Third party URLs
    url(r'^selectable/', include('selectable.urls')),
    url(r'^br/', include('br.urls', namespace=u'br')),
    url(r'^dr/', include('dr.urls', namespace=u'dr')),
    url(r'^locations/', include('locations.urls', namespace=u'locations')),
    url(r'^api/v2/', include('vitalregpro.urls', namespace=u'apiv2')),
    url(r'^api/', include('api.urls', namespace=u'api')),
    url(r'^mnchw/', include('campaigns.urls', namespace=u'mnchw')),
    url(r'incoming/', HttpBackendView.as_view(backend_name='polling')),
    url(r'^messages/', include('messagebox.urls', namespace='messaging')),
    url(r'^reporters/', include('reporters.urls', namespace=u'reporters')),
    url(r'^users/', include('profiles.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# authentication urls
urlpatterns += [
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'backend/login.html'}, name="user-login"),
    url(r'^accounts/logout/$', auth_views.logout_then_login, name="user-logout")
]

br/models.py
import pandas as pd
from django.contrib.auth.models import User
from django.core.cache import cache
from django.core.validators import MinValueValidator
from django.db import models

from common.constants import DATA_SOURCES, DATA_SOURCE_INTERNAL
from locations.models import Location
from reporters.models import Reporter, PersistantConnection
from unicefng.querysets import SearchableLocationQuerySet


class BirthRegistrationQuerySet(SearchableLocationQuerySet):
    pass


class BirthRegistrationManager(models.Manager.from_queryset(BirthRegistrationQuerySet)):
    use_in_migrations = True


class BirthRegistration(models.Model):
    """Stores birth registration records for the different health facilities"""
    reporter = models.ForeignKey(Reporter, blank=True, null=True, related_name="br_birthregistration")
    connection = models.ForeignKey(PersistantConnection, blank=True, null=True, related_name="br_birthregistration")
    location = models.ForeignKey(Location, related_name='birthregistration_records')
    girls_below1 = models.IntegerField(
        help_text='The number of girls registered under 1 year old',
        validators=[MinValueValidator(0)],
        verbose_name='Girls (under 1)')
    girls_1to4 = models.IntegerField(
        help_text='The number of girls registered between 1 and 4 years old',
        validators=[MinValueValidator(0)],
        verbose_name='Girls (1 to 4)')
    girls_5to9 = models.IntegerField(
        help_text='The number of girls registered between 5 and 9 years old',
        validators=[MinValueValidator(0)],
        verbose_name='Girls (5 to 9)')
    girls_10to18 = models.IntegerField(
        help_text='The number of girls registered between 10 and 18 years old',
        validators=[MinValueValidator(0)],
        verbose_name='Girls (10)')
    boys_below1 = models.IntegerField(
        help_text='The number of boys registered under 1 year old',
        validators=[MinValueValidator(0)],
        verbose_name='Boys (under 1)')
    boys_1to4 = models.IntegerField(
        help_text='The number of boys registered between 1 and 4 years old',
        validators=[MinValueValidator(0)],
        verbose_name='Boys (1 to 4)')
    boys_5to9 = models.IntegerField(
        help_text='The number of boys registered between 5 and 9 years old',
        validators=[MinValueValidator(0)],
        verbose_name='Boys (5 to 9)')
    boys_10to18 = models.IntegerField(
        help_text='The number of boys registered between 10 and 18 years old',
        validators=[MinValueValidator(0)],
        verbose_name='Boys (10)')
    time = models.DateTimeField(
        help_text='The UTC timestamp for the record creation')
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    source = models.CharField(
        max_length=32, choices=DATA_SOURCES, default=DATA_SOURCE_INTERNAL)
    disabled = models.BooleanField(default=False)

    objects = BirthRegistrationManager()

    def __unicode__(self):
        return "%s" % (self.pk)

    class Meta:
        permissions = (
            ("can_view", "Can view"),
        )


class CensusResult(models.Model):
    '''Stores population count'''
    location = models.ForeignKey(Location, related_name='census_results')
    year = models.IntegerField()
    population = models.IntegerField()
    growth_rate = models.FloatField()
    under_1_rate = models.FloatField(null=True)
    under_5_rate = models.FloatField(null=True)

    @staticmethod
    def get_dataframe():
        app_cache = cache

        dataframe = app_cache.get('population_estimates')
        if (type(dataframe) is not pd.DataFrame) or dataframe.empty:
            dataframe = generate_population_dataframe()
            app_cache.set('population_estimates', dataframe)

        return dataframe

    @classmethod
    def get_census_dataframe(cls, year):
        db_year = cls.objects.filter(year__lte=year).aggregate(
            max_year=models.Max(u'year')).get(u'max_year')

        qs = cls.objects.filter(year=db_year).annotate(
            loc_id=models.F(u'location__pk')).values(u'year', u'population',
            u'growth_rate', u'loc_id', u'under_1_rate', u'under_5_rate')

        dataframe = pd.DataFrame.from_records(qs).set_index(
            u'loc_id').sort_index()

        return dataframe

    @classmethod
    def get_estimate_dataframe(cls, year, month=None):
        dataframe = cls.get_census_dataframe(year)
        if month is not None:
            if month not in list(range(1, 13)):
                raise ValueError('Invalid month value')

        def _process(row):
            if month is not None:
                growth_rate = ((1 + row['growth_rate']) ** (1 / 12.0)) - 1
                exponent = (year - row['year'] - 1) + month
            else:
                growth_rate = row['growth_rate']
                exponent = (year - row['year'])

            estimate = row['population'] * (
                (1 + (growth_rate / 100)) ** exponent)
            u1_estimate = estimate * row['under_1_rate'] / 100.0
            u5_estimate = estimate * row['under_5_rate'] / 100.0

            return pd.Series(
                [estimate, u1_estimate, u5_estimate],
                index=['estimate', 'u1_estimate', 'u5_estimate'])

        return dataframe.apply(_process, axis=1)


def generate_population_dataframe():
    qs = CensusResult.objects.values(
        'location__pk', 'year', 'population',
        'growth_rate'
    )
    dataframe = pd.DataFrame(list(qs))

    return dataframe.rename(columns={
        'location__pk': 'loc_id',
    })


class Subscription(models.Model):
    subscriber = models.ForeignKey(User)
    locations = models.ManyToManyField(Location)
    is_active = models.BooleanField(default=True)
    last_updated = models.DateTimeField(auto_now=True)

ipd/models.py
# -*- coding: utf-8 -*-
from django.db import models

from common.constants import DATA_SOURCES
from locations.models import Location
from reporters.models import PersistantConnection, Reporter


class Report(models.Model):
    IM_COMMODITIES = (
        ('opv', 'Oral Polio Vaccine'),
        ('vita', 'Vitamin A'),
        ('tt', 'Tetanus Toxoid'),
        ('mv', 'Measles Vaccine'),
        ('bcg', 'Bacille Calmette-Guerin Vaccine'),
        ('yf', 'Yellow Fever'),
        ('hepb', 'Hepatitis B'),
        ('fe', 'Iron Folate'),
        ('dpt', 'Diphtheria'),
        ('deworm', 'Deworming'),
        ('sp', 'Sulphadoxie Pyrimethanol for IPT'),
        ('plus', 'Plus'),
        ('hp', 'Health Promotion'),
        ('fp', 'Family Planning'),
        ('llin', 'Long Lasting Insecticide Nets'),
        ('muac', 'Measurement of Upper Arm Circumference'),
        ('penta', 'Pentavalent Vaccine'),
    )

    reporter = models.ForeignKey(Reporter, blank=True, null=True)
    connection = models.ForeignKey(PersistantConnection, blank=True, null=True)
    location = models.ForeignKey(Location)
    time = models.DateTimeField(db_index=True)
    immunized = models.PositiveIntegerField(blank=True, null=True,
        help_text=u'Total persons immunized')
    commodity = models.CharField(choices=IM_COMMODITIES, max_length=10,
        blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    source = models.CharField(
        choices=DATA_SOURCES, default=DATA_SOURCES[1][0], max_length=32)

    class Meta:
        permissions = (
            (u'can_view', u'Can view'),
        )

    def __str__(self):
        return u'{} ({}) => {}, {}'.format(self.location, self.reporter,
            self.commodity, self.immunized)


class NonCompliance(models.Model):
    NC_REASONS = (
        ('1', 'OPV Safety'),
        ('2', 'Child Sick'),
        ('3', 'Religious Belief'),
        ('4', 'No Felt Need'),
        ('5', 'Political Differences'),
        ('6', 'No Care Giver Consent'),
        ('7', 'Unhappy With Immunization Personnel'),
        ('8', 'Too Many Rounds'),
        ('9', 'Reason Not Given'),
    )

    reporter = models.ForeignKey(Reporter, blank=True, null=True)
    connection = models.ForeignKey(PersistantConnection, blank=True, null=True)
    location = models.ForeignKey(Location)
    time = models.DateTimeField(db_index=True)
    reason = models.CharField(choices=NC_REASONS, max_length=1, blank=True,
        null=True, help_text=u'The stated reason for non-compliance')
    cases = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    source = models.CharField(
        choices=DATA_SOURCES, default=DATA_SOURCES[1][0], max_length=32)


class Shortage(models.Model):
    SHORTAGE_COMMODITIES = (
        ('opv', 'OPV'),
        ('vita', 'Vitamin A'),
        ('tt', 'Tetanus Toxoid'),
        ('mv', 'Measles Vaccine'),
        ('yf', 'Yellow Fever'),
        ('hepb', 'Hepatitis B'),
        ('folate', 'Ferrous Folate'),
        ('dpt', 'Diphtheria'),
        ('deworm', 'Deworming'),
        ('sp', 'Sulphadoxie Pyrimethanol for IPT'),
        ('plus', 'Plus'),
    )

    reporter = models.ForeignKey(Reporter, null=True, blank=True)
    connection = models.ForeignKey(PersistantConnection, null=True, blank=True)
    location = models.ForeignKey(Location)
    time = models.DateTimeField(db_index=True)
    commodity = models.CharField(blank=True, null=True, max_length=10,
        choices=SHORTAGE_COMMODITIES,
        help_text=u'The commodity being reported as having a shortage')
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    source = models.CharField(
        choices=DATA_SOURCES, default=DATA_SOURCES[1][0], max_length=32)

    def __str__(self):
        return u'{} ({}) => {}'.format(self.reporter, self.location,
            self.commodity)

br/forms.py
from django import forms
from br.models import BirthRegistration


class BirthRegistrationModelForm(forms.ModelForm):
    class Meta:
        model = BirthRegistration
        fields = ('girls_below1', 'girls_1to4', 'girls_5to9', 'girls_10to18',
                  'boys_below1', 'boys_1to4', 'boys_5to9', 'boys_10to18')


class ReportDeleteForm(forms.Form):
    reports = forms.ModelMultipleChoiceField(
        queryset=BirthRegistration.objects.all(),
        required=False, widget=forms.CheckboxSelectMultiple)

br/api/views.py
# -*- coding: utf-8 -*-
from django.http import JsonResponse
from django.utils.timezone import now
from drf_yasg.utils import swagger_auto_schema

from br.api.utils import get_api_data, get_estimate_dataframe
from br.models import CensusResult
from br.utils import extract_reporting_records, get_report_year_range
from locations.models import Location


@swagger_auto_schema(auto_schema=None)
def dashboard(request):
    level = request.GET.get('level', 'country')
    try:
        year = int(request.GET.get('year'))
    except TypeError, ValueError:
        year = None
    try:
        month = int(request.GET.get('month'))
    except TypeError, ValueError:
        month = None

    return JsonResponse(get_api_data(level, year, month))


@swagger_auto_schema(auto_schema=None)
def get_projection_data(request):
    current_timestamp = now()
    start_year, end_year = get_report_year_range()

    # extract location
    location_id = request.GET.get('location')
    try:
        location = Location.objects.get(pk=location_id)
    except Exception:
        return JsonResponse(dict(message='Location not found', status='error'), status=404)

    # extract year
    try:
        year = int(request.GET.get('year'))
        if year < start_year or year > end_year:
            return JsonResponse(dict(message='Invalid year', status='error'), status=400)
    except (TypeError, ValueError):
        year = current_timestamp.year

    # extract month
    month_raw = request.GET.get('month')
    if month_raw is None or month_raw == '':
        month = None
    else:
        try:
            month = int(month_raw)
        except ValueError:
            month = current_timestamp.month
    if month is not None:
        if month < 1 or month > 12:
            return JsonResponse(dict(message='Invalid month', status='error'), status=400)

    reporting_df, prior_u1_df = extract_reporting_records(location, year, month)
    # census_result = CensusResult.get_estimate_dataframe(year, month).reset_index()
    census_result = get_estimate_dataframe(year, month).reset_index()

    col_names = ['loc_name', 'loc_id']
    if location.level == 0:
        group_columns = ['state', 'state_id']
    elif location.level == 2:
        group_columns = ['lga', 'lga_id']
    else:
        return JsonResponse(dict(message='Invalid location specified', status='error'), status=400)

    if reporting_df.empty:
        return JsonResponse(dict(data=[], status='empty'))

    summed_reporting_df = reporting_df.groupby(
        group_columns).sum().reset_index()
    summed_prior_u1_df = prior_u1_df.groupby(
        group_columns[1]).sum().reset_index()

    combined_df = summed_reporting_df.merge(
        summed_prior_u1_df, on=group_columns[1], suffixes=('', '_prior')
    ).merge(
        census_result, left_on=group_columns[1], right_on='loc_id'
    ).rename(
        columns={k: v for k, v in zip(group_columns, col_names)}
    ).round({
        'u1_estimate': 0,
        'u5_estimate': 0
    })
    combined_df['u5_and_u1_prior'] = combined_df['u5'] + combined_df['u1_prior']
    combined_df['u1_diff'] = combined_df['u1'] - combined_df['u1_estimate']
    combined_df['u5_diff'] = combined_df['u5'] - combined_df['u5_estimate']
    combined_df['u5_diff_with_prior'] = combined_df['u5'] - combined_df['u5_estimate'] + combined_df['u1_prior']

    return JsonResponse(dict(data=combined_df.to_dict(orient='records'), status='ok'))

br/templates/backend/_layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'vendor/bootstrap5/css/bootstrap.min.css' %}">
  {% block stylesheets %}{% endblock stylesheets %}
  <title>{{ page_title }}</title>
</head>
<body>
  <header class="py-3 border-bottom">
      <div class="container-fluid d-grid gap-3 align-items-center" style="grid-template-columns: 1fr 2fr;">
        <h4>Rapid<strong>SMS</strong></h4>
        <div class="d-flex align-items-center justify-content-end">
          <div class="flex-shrink-0 dropdown text-end">
            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownMenu" data-bs-toggle="dropdown" aria-expanded="false">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20">
                <title>Settings</title>
                <path fill="none" d="M0 0h24v24H0z"/>
                <path d="M2.132 13.63a9.942 9.942 0 0 1 0-3.26c1.102.026 2.092-.502 2.477-1.431.385-.93.058-2.004-.74-2.763a9.942 9.942 0 0 1 2.306-2.307c.76.798 1.834 1.125 2.764.74.93-.385 1.457-1.376 1.43-2.477a9.942 9.942 0 0 1 3.262 0c-.027 1.102.501 2.092 1.43 2.477.93.385 2.004.058 2.763-.74a9.942 9.942 0 0 1 2.307 2.306c-.798.76-1.125 1.834-.74 2.764.385.93 1.376 1.457 2.477 1.43a9.942 9.942 0 0 1 0 3.262c-1.102-.027-2.092.501-2.477 1.43-.385.93-.058 2.004.74 2.763a9.942 9.942 0 0 1-2.306 2.307c-.76-.798-1.834-1.125-2.764-.74-.93.385-1.457 1.376-1.43 2.477a9.942 9.942 0 0 1-3.262 0c.027-1.102-.501-2.092-1.43-2.477-.93-.385-2.004-.058-2.763.74a9.942 9.942 0 0 1-2.307-2.306c.798-.76 1.125-1.834.74-2.764-.385-.93-1.376-1.457-2.477-1.43zM12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
              </svg>
            </a>
            <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownMenu">
              {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'br:help' %}">BR help</a></li>
                {% if perms.br.change_birthregistration %}
                <li><a class="dropdown-item" href="{% url 'br:reports_list' %}">BR reports</a></li>
                <li><a class="dropdown-item" href="{% url 'locations:center_list' %}">BR centers</a></li>
                <div class="dropdown-divider"></div>
                {% endif %}
                {% if perms.dr.change_deathreport %}
                <li><a class="dropdown-item" href="{% url 'dr:dr_report_list' %}">DR reports</a></li>
                <li><a class="dropdown-item" href="{% static 'documents/DRFORM.pdf' %}">DR manual</a></li>
                <div class="dropdown-divider"></div>
                {% endif %}
                {% if perms.ipd.change_report %}
                <li><a class="dropdown-item" href="{% url 'mnchw:campaign_list' %}">MNCHW campaigns</a></li>
                <div class="dropdown-divider"></div>
                {% endif %}
                {% if perms.reporters.change_reporter %}
                <li><a href="{% url 'reporters:reporter_list' %}" class="dropdown-item">Reporters</a></li>
                <div class="dropdown-divider"></div>
                {% endif %}
                {% if perms.auth.change_user %}
                <li><a href="{% url 'users:users_list' %}" class="dropdown-item">Users</a></li>
                <div class="dropdown-divider"></div>
                {% endif %}
                <li><a class="dropdown-item" href="{% url 'messaging:message_list' %}">Messages</a></li>
                <div class="dropdown-divider"></div>
                <li>
                  <a class="dropdown-item" href="{% url 'user-logout' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" width="20" height="20">
                      <path fill-rule="evenodd" d="M3 3a1 1 0 00-1 1v12a1 1 0 102 0V4a1 1 0 00-1-1zm10.293 9.293a1 1 0 001.414 1.414l3-3a1 1 0 000-1.414l-3-3a1 1 0 10-1.414 1.414L14.586 9H7a1 1 0 100 2h7.586l-1.293 1.293z" clip-rule="evenodd" />
                    </svg>
                    &nbsp; Log Out
                  </a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
  </header>
  <div class="container-fluid">
    <div class="row">
      <main class="col-md-12 ms-sm-auto bg-dark bg-opacity-10">
        {% block content %}{% endblock content %}
      </main>
    </div>
  </div>
  <script src="{% static 'vendor/bootstrap5/js/bootstrap.bundle.min.js' %}"></script>
  {% block scripts %}{% endblock scripts %}
</body>
</html>

br/templates/backend/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'vendor/bootstrap5/css/bootstrap.min.css' %}">
  <title>Login</title>
  <style>
    html,body {
      height: 100%;
    }

    body {
      display: flex;
      align-items: center;
      padding-top: 40px;
      padding-bottom: 40px;
    }

    .form-signin {
      width: 100%;
      max-width: 330px;
      padding: 15px;
      margin: auto;
    }

    .form-signin .form-floating:focus-within {
      z-index: 2;
    }

    .form-signin input[type="text"] {
      margin-bottom: -1px;
      border-bottom-right-radius: 0;
      border-bottom-left-radius: 0;
    }
    
    .form-signin input[type="password"] {
      margin-bottom: 10px;
      border-top-right-radius: 0;
      border-top-left-radius: 0;
    }
  </style>
</head>
<body class="text-center">
  <main class="form-signin">
    <form method="post">
      {% csrf_token %}
      <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
      <div class="form-floating">
        <input id="username" type="text" name="username" class="form-control" placeholder="Username">
        <label for="username">Username</label>
      </div>
      <div class="form-floating">
        <input id="password" type="password" name="password" class="form-control" placeholder="Password">
        <label for="password">Password</label>
      </div>
      <button class="w-100 btn btn-lg btn-primary" type="submit">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" width="20" height="20">
          <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
        </svg>
        Sign in
      </button>
    </form>
  </main>
</body>
</html>

br/templates/backend/message_list.html
{% extends 'backend/_layout.html' %}
{% load staticfiles %}
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'vendor/flatpickr/flatpickr.min.css' %}">
{% endblock stylesheets %}
{% block content %}
<div class="row">
  <div class="col">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-1 pb-1 mb-1 border-bottom">
      <h3>{{ page_title }}</h3>
    </div>
  </div>
</div>
<div class="row">
  <div class="col">
    <form id="filter_form">
      <div class="card border-light mb-3">
        <div class="card-body">
          <div class="row g-3">
            <div class="col-md-4 col-sm-12">
              <input type="text" class="form-control" id="{{ filter_form.phone.id_for_label }}" name="{{ filter_form.phone.name }}" value="{{ filter_form.phone.value|default:'' }}" placeholder="Phone">
            </div>
            <div class="col-md-4 col-sm-12">
              <input type="text" class="form-control date-picker" id="{{ filter_form.date.id_for_label }}" name="{{ filter_form.date.name }}" value="{{ filter_form.date.value|default:'' }}" placeholder="Date">
            </div>
            <div class="col-md-4 col-sm-12">
              <button type="submit" class="btn btn-dark">Filter</button>
              <a href="{% url 'messaging:message_list' %}" class="btn btn-light mx-1">Clear</a>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-hover table-sm table-striped">
            <thead>
              <tr>
                <th>Phone</th>
                <th>Time</th>
                <th>Direction</th>
                <th>Message</th>
              </tr>
            </thead>
            <tbody>
              {% for message in messages %}
              <tr>
                <td>{{ message.connection.identity }}</td>
                <td>{{ message.date|date:'d/m/Y H:i:s' }}</td>
                <td>{{ message.get_direction_display }}</td>
                <td>{{ message.text }}</td>
              </tr>
              {% empty %}
              <tr>
                <td class="table-warning" colspan="4">No records found</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% include 'backend/pagination.html' %}
{% endblock content %}
{% block scripts %}
<script src="{% static 'vendor/flatpickr/flatpickr.min.js' %}"></script>
<script>
  let loader = function () {
    flatpickr('.date-picker', {
      dateFormat: 'm/d/Y'
    });
  };

  document.addEventListener('DOMContentLoaded', loader);
</script>
{% endblock scripts %}